package com.klmobile.passwordmanager.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF0060A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C38)
val md_theme_light_secondary = Color(0xFF006492)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2F)
val md_theme_light_tertiary = Color(0xFF7F5600)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDAF)
val md_theme_light_onTertiaryContainer = Color(0xFF281800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF251A00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF251A00)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFFFEFD3)
val md_theme_light_inverseSurface = Color(0xFF3F2E00)
val md_theme_light_inversePrimary = Color(0xFFA2C9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0060A9)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA2C9FF)
val md_theme_dark_onPrimary = Color(0xFF00315B)
val md_theme_dark_primaryContainer = Color(0xFF004881)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E4FF)
val md_theme_dark_secondary = Color(0xFF8CCEFF)
val md_theme_dark_onSecondary = Color(0xFF00344E)
val md_theme_dark_secondaryContainer = Color(0xFF004B6F)
val md_theme_dark_onSecondaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_tertiary = Color(0xFFFDBB4A)
val md_theme_dark_onTertiary = Color(0xFF432C00)
val md_theme_dark_tertiaryContainer = Color(0xFF614000)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDAF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF251A00)
val md_theme_dark_onBackground = Color(0xFFFFDF9C)
val md_theme_dark_surface = Color(0xFF251A00)
val md_theme_dark_onSurface = Color(0xFFFFDF9C)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF251A00)
val md_theme_dark_inverseSurface = Color(0xFFFFDF9C)
val md_theme_dark_inversePrimary = Color(0xFF0060A9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA2C9FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF006BBB)
val CustomColor1 = Color(0xFF1332E1)
val light_CustomColor1 = Color(0xFF2D46EF)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFDFE0FF)
val light_onCustomColor1Container = Color(0xFF000C61)
val dark_CustomColor1 = Color(0xFFBCC2FF)
val dark_onCustomColor1 = Color(0xFF001999)
val dark_CustomColor1Container = Color(0xFF0027D5)
val dark_onCustomColor1Container = Color(0xFFDFE0FF)